%YAML:1.0

#common parameters
imu_topic: "/sync/imu"
image_topic: "/sync/cam1/img"
output_path: "/home/shaozu/output/"

#camera calibration 
model_type: PINHOLE
camera_name: camera
image_width: 640
image_height: 512
distortion_parameters:
   k1: -0.03481376032657559
   k2: 0.00617761827419759
   p1: -0.014648049835094821
   p2: 0.010177338964542818
projection_parameters:
   fx: 345.68502144187477
   fy: 346.00773090673493
   cx: 321.3651287125868
   cy: 257.24682412508986

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning.                        
#If you choose 0 or 1, you should write down the following matrix.
#Rotation from camera frame to imu frame, imu^R_cam
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.06874549, 0.04111236, 0.99678675,
           -0.99671705, 0.0456642, 0.06685727, 
           -0.04276881, -0.99811049, 0.04411659]
#Translation from camera frame to imu frame, imu^T_cam
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [0.08452888, 0.0531234, -0.0138501]

#feature traker paprameters max_cnt: 150 
max_cnt: 80            # max feature number in feature tracking
min_dist: 26            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 0             # if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time 0.04
max_num_iterations: 8   # max solver itrations, to guarantee real time 8
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance 
acc_n: 0.04          # accelerometer measurement noise standard deviation. 0.04 
gyr_n: 0.00375         # gyroscope measurement noise standard deviation.     0.0004
acc_w: 0.0004         # accelerometer bias random work noise standard deviation.  0.0004
gyr_w: 0.000375       # gyroscope bias random work noise standard deviation.     #4.0e-5 2.0e-6
g_norm: 9.810     # gravity magnitude 9.81007

#loop closure parameters
loop_closure: 0                    # start loop closure
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
fast_relocalization: 0             # useful in real-time and large project
pose_graph_save_path: "/home/shaozu/output/pose_graph/" # save and load path

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#rolling shutter parameters
rolling_shutter: 0                  # 0: global shutter camera, 1: rolling shutter camera
rolling_shutter_tr: 0               # unit: s. rolling shutter read out time per frame (from data sheet). 

#visualization parameters
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
visualize_imu_forward: 0        # output imu forward propogation to achieve low latency and high frequence results
visualize_camera_size: 0.4      # size of camera marker in RVIZ
